# Generated by Django 5.1.3 on 2024-12-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Выдана', 'Выдана')], default='available', max_length=10)),
            ],
        ),
    ]
